# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsIamUser < Formula
  desc "Manage your IAM credentials easily."
  homepage "https://github.com/conijnio/aws-iam-user"
  version "0.2.7"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.7/aws-iam-user_0.2.7_darwin_amd64.tar.gz"
      sha256 "9a2acff261a81235e6c801d91d40403eb0a688cb00173dc0a22228002459a11a"

      def install
        bin.install "aws-iam-user"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.7/aws-iam-user_0.2.7_darwin_arm64.tar.gz"
      sha256 "4679875fd4484f7d2bc3e850eb51beb4daca8b975cc50efb89ed057448f21d2b"

      def install
        bin.install "aws-iam-user"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.7/aws-iam-user_0.2.7_linux_amd64.tar.gz"
      sha256 "823350c9fa7437f52c312857ceccc94e649d75b8b4e966ec493e5f92f631672c"

      def install
        bin.install "aws-iam-user"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.7/aws-iam-user_0.2.7_linux_arm64.tar.gz"
      sha256 "21d1c80d7f575d45044e548b64c598272f82f94c3f5cb5ae9b799947ebfce5fb"

      def install
        bin.install "aws-iam-user"
      end
    end
  end

  test do
    system "#{bin}/aws-iam-user -v"
  end
end
