# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsIamUser < Formula
  desc "Manage your IAM credentials easily."
  homepage "https://github.com/conijnio/aws-iam-user"
  version "0.2.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.0/aws-iam-user_0.2.0_darwin_amd64.tar.gz"
      sha256 "c9b7660fc8e7cbcb67c8fdc9ac9dc20617af2dccf5d3c496cc7be2bf0acf9d3a"

      def install
        bin.install "aws-iam-user"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.0/aws-iam-user_0.2.0_darwin_arm64.tar.gz"
      sha256 "16a69054013785a2dcc101fe3d7e5e35bdbeb87c83c04d6978013bd550165569"

      def install
        bin.install "aws-iam-user"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.0/aws-iam-user_0.2.0_linux_amd64.tar.gz"
      sha256 "362a995f498abae48efffa90682e2a42499d3666b356f9b831a9ca53834f9b8d"

      def install
        bin.install "aws-iam-user"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conijnio/aws-iam-user/releases/download/v0.2.0/aws-iam-user_0.2.0_linux_arm64.tar.gz"
      sha256 "fc37fbb3a78c809d0a9403fb0c0c5d3c2d99e96c38b583cec886f52e420ed937"

      def install
        bin.install "aws-iam-user"
      end
    end
  end

  test do
    system "#{bin}/aws-iam-user -v"
  end
end
